<?php

/**
 * @file
 * Contains faq.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function faq_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the faq module.
    case 'help.page.faq':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('display faq, filter by texonomy') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function faq_theme():array {
  return [
    'block_container' => [
        'variables' => [ 'data' => null],
        'template'  => 'block--faq-by-taxonomy'
    ],
    'taxonomy_tab_component' => [
      'template'  => 'taxonomy-tab-component'
    ],
    'taxonomy_faq_component'=>[
      'template'  => 'taxonomy-faq-component'
    ]
  ];
}

function faq_preprocess_node__page(array &$variables) : void {
  $variables['#attached']['library'][] = 'faq/faq';
}
